//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAIr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeAIr.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add XML comments that match the following code. Do not shorten the source code..
        /// </summary>
        public static string ChatKindEnum_AddXmlComments {
            get {
                return ResourceManager.GetString("ChatKindEnum_AddXmlComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the following code according its comments:.
        /// </summary>
        public static string ChatKindEnum_CompleteCodeAccordingComments {
            get {
                return ResourceManager.GetString("ChatKindEnum_CompleteCodeAccordingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain the following code:.
        /// </summary>
        public static string ChatKindEnum_ExplainCode {
            get {
                return ResourceManager.GetString("ChatKindEnum_ExplainCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler reported an error in the source code. Help fix the code. Error: .
        /// </summary>
        public static string ChatKindEnum_FixBuildError {
            get {
                return ResourceManager.GetString("ChatKindEnum_FixBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate commit message according the following git patch. Give in your reply only the commit message without additional information. Do not wrap the whole answer in any quotes..
        /// </summary>
        public static string ChatKindEnum_GenerateCommitMessage {
            get {
                return ResourceManager.GetString("ChatKindEnum_GenerateCommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a set of unit tests for the following code. Provide only one code snippet in your answer, without any additional information. Add XML comments for each test that describe what the test checks. Write code for the {0} test framework..
        /// </summary>
        public static string ChatKindEnum_GenerateUnitTests {
            get {
                return ResourceManager.GetString("ChatKindEnum_GenerateUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the search query given to you, carefully examine all the attached files and find all the places that match the query. Your response should be a list in the following JSON format: `{ &quot;matches&quot;: [ {&quot;fullpath&quot;: &quot;full path to the file&quot;, &quot;found_text&quot;:&quot;a matched word sequence from document&quot;, &quot;confidence_level&quot;:a_level_of_your_confidence, &quot;line&quot;:line_number_of_found_text, &quot;reason&quot;:&quot;a reason why you include this item to your result&quot;} ] }`. `found_text` - 5-10 words from the document that you think match the s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChatKindEnum_NaturalLanguageSearch {
            get {
                return ResourceManager.GetString("ChatKindEnum_NaturalLanguageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize the following code:.
        /// </summary>
        public static string ChatKindEnum_OptimizeCode {
            get {
                return ResourceManager.GetString("ChatKindEnum_OptimizeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest filling the whole line where `{0}` is written in the following code. Give in your reply only new piece of code without additional information and without the code I provide you..
        /// </summary>
        public static string ChatKindEnum_SuggestWholeLine {
            get {
                return ResourceManager.GetString("ChatKindEnum_SuggestWholeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;｜fim▁hole｜&gt;.
        /// </summary>
        public static string ChatKindEnum_SuggestWholeLine_Anchor {
            get {
                return ResourceManager.GetString("ChatKindEnum_SuggestWholeLine_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain selected block of code..
        /// </summary>
        public static string Code_NoSelectedCode {
            get {
                return ResourceManager.GetString("Code_NoSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup API endpoint and access token in FreeAIr control panel. If you are using local LLM enter any string into token option..
        /// </summary>
        public static string Code_NoToken {
            get {
                return ResourceManager.GetString("Code_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string UI_Answer {
            get {
                return ResourceManager.GetString("UI_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string UI_Choose {
            get {
                return ResourceManager.GetString("UI_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load only free models.
        /// </summary>
        public static string UI_LoadOnlyFreeModels {
            get {
                return ResourceManager.GetString("UI_LoadOnlyFreeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in main editor....
        /// </summary>
        public static string UI_OpenInEditor {
            get {
                return ResourceManager.GetString("UI_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string UI_Prompt {
            get {
                return ResourceManager.GetString("UI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove chat.
        /// </summary>
        public static string UI_RemoveChat {
            get {
                return ResourceManager.GetString("UI_RemoveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat....
        /// </summary>
        public static string UI_StartDiscussion {
            get {
                return ResourceManager.GetString("UI_StartDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string UI_StopWaiting {
            get {
                return ResourceManager.GetString("UI_StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page....
        /// </summary>
        public static string UI_UpdatePage {
            get {
                return ResourceManager.GetString("UI_UpdatePage", resourceCulture);
            }
        }
    }
}
