//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAIr.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeAIr.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add custom file....
        /// </summary>
        public static string Add_custom_file {
            get {
                return ResourceManager.GetString("Add custom file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add custom file to chat context.
        /// </summary>
        public static string Add_custom_file_to_chat_context {
            get {
                return ResourceManager.GetString("Add_custom_file_to_chat_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new action.
        /// </summary>
        public static string Add_new_action {
            get {
                return ResourceManager.GetString("Add_new_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new agent.
        /// </summary>
        public static string Add_new_agent {
            get {
                return ResourceManager.GetString("Add_new_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new items to context.
        /// </summary>
        public static string Add_new_items_to_context {
            get {
                return ResourceManager.GetString("Add_new_items_to_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new items to context:.
        /// </summary>
        public static string Add_new_items_to_context1 {
            get {
                return ResourceManager.GetString("Add_new_items_to_context1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agent name.
        /// </summary>
        public static string Agent_name {
            get {
                return ResourceManager.GetString("Agent_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agent system prompt:.
        /// </summary>
        public static string Agent_system_prompt {
            get {
                return ResourceManager.GetString("Agent_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AI chat list.
        /// </summary>
        public static string AI_chat_list {
            get {
                return ResourceManager.GetString("AI chat list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AI is getting colder, it nothing is asked about.
        /// </summary>
        public static string AI_is_getting_colder {
            get {
                return ResourceManager.GetString("AI_is_getting_colder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply changes.
        /// </summary>
        public static string Apply_changes {
            get {
                return ResourceManager.GetString("Apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available agents:.
        /// </summary>
        public static string Available_agents {
            get {
                return ResourceManager.GetString("Available_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build Natural Language Outlines Json File.
        /// </summary>
        public static string Build_Natural_Language_Outlines_Json_File {
            get {
                return ResourceManager.GetString("Build_Natural_Language_Outlines_Json_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel chat.
        /// </summary>
        public static string Cancel_chat {
            get {
                return ResourceManager.GetString("Cancel_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create a new file. Please create the file manually..
        /// </summary>
        public static string Cannot_create_a_new_file__Please {
            get {
                return ResourceManager.GetString("Cannot_create_a_new_file__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot determine the position of found entry. The file will be open without selection..
        /// </summary>
        public static string Cannot_determine_the_position_of {
            get {
                return ResourceManager.GetString("Cannot_determine_the_position_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot replace context document body. Please replace manually..
        /// </summary>
        public static string Cannot_replace_context_document_body {
            get {
                return ResourceManager.GetString("Cannot_replace_context_document_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot replace selected text. Please replace the selected text manually..
        /// </summary>
        public static string Cannot_replace_selected_text__Please {
            get {
                return ResourceManager.GetString("Cannot_replace_selected_text__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat context:.
        /// </summary>
        public static string Chat_context {
            get {
                return ResourceManager.GetString("Chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose agent (with a non-empty token) for a chat:.
        /// </summary>
        public static string Choose_agent__with_a_non_empty_token {
            get {
                return ResourceManager.GetString("Choose_agent__with_a_non_empty_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose chat agent{0}....
        /// </summary>
        public static string Choose_chat_agent {
            get {
                return ResourceManager.GetString("Choose_chat_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose context item to replace:.
        /// </summary>
        public static string Choose_context_item_to_replace {
            get {
                return ResourceManager.GetString("Choose_context_item_to_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose context item to replace its content with this code part.
        /// </summary>
        public static string Choose_context_item_to_replace_its {
            get {
                return ResourceManager.GetString("Choose_context_item_to_replace_its", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose model from this api endpoint.
        /// </summary>
        public static string Choose_model_from_this_api_endpoint {
            get {
                return ResourceManager.GetString("Choose_model_from_this_api_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose OpenRouter model.
        /// </summary>
        public static string Choose_OpenRouter_model {
            get {
                return ResourceManager.GetString("Choose_OpenRouter_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the available agent:.
        /// </summary>
        public static string Choose_the_available_agent {
            get {
                return ResourceManager.GetString("Choose_the_available_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the MCP tools you want to provide to LLM:.
        /// </summary>
        public static string Choose_the_MCP_tools_you_want_to {
            get {
                return ResourceManager.GetString("Choose_the_MCP_tools_you_want_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose this chat agent. These changes are not shared across other chats..
        /// </summary>
        public static string Choose_this_chat_agent {
            get {
                return ResourceManager.GetString("Choose this chat agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (chosen).
        /// </summary>
        public static string chosen {
            get {
                return ResourceManager.GetString("chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chosen model:.
        /// </summary>
        public static string Chosen_model {
            get {
                return ResourceManager.GetString("Chosen_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to copy to clipboard.
        /// </summary>
        public static string Click_to_copy_to_clipboard {
            get {
                return ResourceManager.GetString("Click_to_copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  (cloned).
        /// </summary>
        public static string cloned {
            get {
                return ResourceManager.GetString("cloned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot obtain selected block of code..
        /// </summary>
        public static string Code_NoSelectedCode {
            get {
                return ResourceManager.GetString("Code_NoSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please setup API endpoint and access token in FreeAIr control panel. If you are using local LLM enter any string into token option..
        /// </summary>
        public static string Code_NoToken {
            get {
                return ResourceManager.GetString("Code_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commented Line.
        /// </summary>
        public static string Commented_Line {
            get {
                return ResourceManager.GetString("Commented_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confidence.
        /// </summary>
        public static string Confidence {
            get {
                return ResourceManager.GetString("Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context size:.
        /// </summary>
        public static string Context_size {
            get {
                return ResourceManager.GetString("Context_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new file with this code part.
        /// </summary>
        public static string Create_new_file_with_this_code_part {
            get {
                return ResourceManager.GetString("Create_new_file_with_this_code_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current json is different from the saved one. Consider saving your changes..
        /// </summary>
        public static string Current_json_is_different_from_the {
            get {
                return ResourceManager.GetString("Current_json_is_different_from_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete from context.
        /// </summary>
        public static string Delete_from_context {
            get {
                return ResourceManager.GetString("Delete from context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected action.
        /// </summary>
        public static string Delete_selected_action {
            get {
                return ResourceManager.GetString("Delete_selected_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected agent.
        /// </summary>
        public static string Delete_selected_agent {
            get {
                return ResourceManager.GetString("Delete_selected_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docker image for {0} MCP server installed. Please setup FreeAIr to work with the server..
        /// </summary>
        public static string Docker_image_for__0__MCP_server_installed {
            get {
                return ResourceManager.GetString("Docker_image_for__0__MCP_server_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit chat tools....
        /// </summary>
        public static string Edit_chat_tools {
            get {
                return ResourceManager.GetString("Edit chat tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit FreeAIr options. Changes that made do not affects your opened chats..
        /// </summary>
        public static string Edit_FreeAIr_options {
            get {
                return ResourceManager.GetString("Edit_FreeAIr_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit the MCP tools for the selected chat. These changes are not shared across other chats..
        /// </summary>
        public static string Edit_the_MCP_tools_for_the_selected_chat {
            get {
                return ResourceManager.GetString("Edit the MCP tools for the selected chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Embedding generate agent:.
        /// </summary>
        public static string Embedding_generate_agent {
            get {
                return ResourceManager.GetString("Embedding generate agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoint:.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your prompt here. Press / to open commands. Press # to choose solution item. Press Ctrl + Enter to send your prompt..
        /// </summary>
        public static string Enter_your_prompt_here__Press___to {
            get {
                return ResourceManager.GetString("Enter_your_prompt_here__Press___to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occurred.
        /// </summary>
        public static string Error_occurred {
            get {
                return ResourceManager.GetString("Error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Every MCP server is found, and pinged successfully. Changes was saved successfully..
        /// </summary>
        public static string Every_MCP_server_is_found__and_pinged {
            get {
                return ResourceManager.GetString("Every_MCP_server_is_found__and_pinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Name.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder does not exists yet. Save NLO Json file to create the folder..
        /// </summary>
        public static string Folder_does_not_exists_yet__Save {
            get {
                return ResourceManager.GetString("Folder_does_not_exists_yet__Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force use chosen NLO agent.
        /// </summary>
        public static string Force_use_chosen_NLO_agent {
            get {
                return ResourceManager.GetString("Force_use_chosen_NLO_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found text.
        /// </summary>
        public static string Found_text {
            get {
                return ResourceManager.GetString("Found_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr Agent Configuration Window.
        /// </summary>
        public static string FreeAIr_Agent_Configuration_Window {
            get {
                return ResourceManager.GetString("FreeAIr_Agent_Configuration_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr available support.
        /// </summary>
        public static string FreeAIr_available_support {
            get {
                return ResourceManager.GetString("FreeAIr_available_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr Natural Language Outlines.
        /// </summary>
        public static string FreeAIr_Natural_Language_Outlines {
            get {
                return ResourceManager.GetString("FreeAIr_Natural_Language_Outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr NLO Json file generation.
        /// </summary>
        public static string FreeAIr_NLO_Json_file_generation {
            get {
                return ResourceManager.GetString("FreeAIr_NLO_Json_file_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr options file does not found.
        /// </summary>
        public static string FreeAIr_options_file_does_not_found {
            get {
                return ResourceManager.GetString("FreeAIr_options_file_does_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FreeAIr Support Action Configuration Window.
        /// </summary>
        public static string FreeAIr_Support_Action_Configuration {
            get {
                return ResourceManager.GetString("FreeAIr_Support_Action_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated {0} comments:.
        /// </summary>
        public static string Generated__0__comments {
            get {
                return ResourceManager.GetString("Generated__0__comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GitHub MCP server installed SUCCESSFULLY..
        /// </summary>
        public static string GitHub_MCP_server_installed_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("GitHub_MCP_server_installed_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In progress ({0}/{1})....
        /// </summary>
        public static string In_progress___0___1 {
            get {
                return ResourceManager.GetString("In_progress___0___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation GitHub MCP server fails. Please install it manually..
        /// </summary>
        public static string Installation_GitHub_MCP_server_fails {
            get {
                return ResourceManager.GetString("Installation_GitHub_MCP_server_fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed and Ready.
        /// </summary>
        public static string Installed_and_Ready {
            get {
                return ResourceManager.GetString("Installed_and_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid json. Fix json and try again..
        /// </summary>
        public static string Invalid_json__Fix_json_and_try_again {
            get {
                return ResourceManager.GetString("Invalid_json__Fix_json_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Its prompt template.
        /// </summary>
        public static string Its_prompt_template {
            get {
                return ResourceManager.GetString("Its_prompt_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json cannot be deserialized because of:.
        /// </summary>
        public static string Json_cannot_be_deserialized_because {
            get {
                return ResourceManager.GetString("Json_cannot_be_deserialized_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP server is found, and pinged successfully..
        /// </summary>
        public static string MCP_server_is_found__and_pinged_successfully {
            get {
                return ResourceManager.GetString("MCP_server_is_found__and_pinged_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model list cannot be loaded.
        /// </summary>
        public static string Model_list_cannot_be_loaded {
            get {
                return ResourceManager.GetString("Model_list_cannot_be_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model list is loading....
        /// </summary>
        public static string Model_list_is_loading {
            get {
                return ResourceManager.GetString("Model_list_is_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected action down.
        /// </summary>
        public static string Move_selected_action_down {
            get {
                return ResourceManager.GetString("Move_selected_action_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected action up.
        /// </summary>
        public static string Move_selected_action_up {
            get {
                return ResourceManager.GetString("Move_selected_action_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected agent down.
        /// </summary>
        public static string Move_selected_agent_down {
            get {
                return ResourceManager.GetString("Move_selected_agent_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected agent up.
        /// </summary>
        public static string Move_selected_agent_up {
            get {
                return ResourceManager.GetString("Move_selected_agent_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Natural Language Outlines file path.
        /// </summary>
        public static string Natural_Language_Outlines_file_path {
            get {
                return ResourceManager.GetString("Natural_Language_Outlines_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Natural language search results.
        /// </summary>
        public static string Natural_language_search_results {
            get {
                return ResourceManager.GetString("Natural_language_search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NLO extract action:.
        /// </summary>
        public static string NLO_extract_action {
            get {
                return ResourceManager.GetString("NLO extract action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NLO extract agent:.
        /// </summary>
        public static string NLO_extract_agent {
            get {
                return ResourceManager.GetString("NLO extract agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  NLO embedding file(s) path depends on solution name. These files are useful for natural language search feature of FreeAIr. FreeAIr will use these embeddings to narrow down the search scope. It is recommended to actualize these files before every commit to keep embeddings in sync with your codebase..
        /// </summary>
        public static string NLOG_Tooltip10 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Checked tree items will be updated with a new embeddings, unchecked items will reuse the existing embeddings..
        /// </summary>
        public static string NLOG_Tooltip20 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  FreeAIr process C# files with Roslyn, for any other file &apos;NLO extract agent&apos; is used. This is an agent to extract natural language outlines from a source file if FreeAIr does not know its syntax tree and cannot extract NLOs from its body natively. If you choose &apos;Force use chosen NLO agent&apos; then selected agent will be used for every processed file..
        /// </summary>
        public static string NLOG_Tooltip30 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &apos;Embedding generate agent&apos; is an agent to generate the embeddings from gathered natural language outlines..
        /// </summary>
        public static string NLOG_Tooltip40 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Natural language outlines are used to apply RAG (retrieval augmented generation) for natural language search, and based on the paper https://arxiv.org/html/2408.04820v4.
        /// </summary>
        public static string NLOG_Tooltip50 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No comments applied.
        /// </summary>
        public static string No_comments_applied {
            get {
                return ResourceManager.GetString("No_comments_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No comments for the file {0} applied.
        /// </summary>
        public static string No_comments_for_file__0__applied {
            get {
                return ResourceManager.GetString("No_comments_for_file__0__applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No dependencies found. This may occurs because Intellisense is not loaded (yet), or the context item is not a .Net source code..
        /// </summary>
        public static string No_dependencies_found__This_may_occurs {
            get {
                return ResourceManager.GetString("No_dependencies_found__This_may_occurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Installed.
        /// </summary>
        public static string Not_Installed {
            get {
                return ResourceManager.GetString("Not_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not started.
        /// </summary>
        public static string Not_started {
            get {
                return ResourceManager.GetString("Not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open contol center....
        /// </summary>
        public static string Open_contol_center {
            get {
                return ResourceManager.GetString("Open contol center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open item in new window.
        /// </summary>
        public static string Open_item_in_new_window {
            get {
                return ResourceManager.GetString("Open_item_in_new_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options file {0} has been deleted..
        /// </summary>
        public static string Options_file__0__has_been_deleted {
            get {
                return ResourceManager.GetString("Options_file__0__has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options inside Visual Studio has been deleted..
        /// </summary>
        public static string Options_inside_Visual_Studio_has {
            get {
                return ResourceManager.GetString("Options_inside_Visual_Studio_has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options json is not empty. Overwrite?.
        /// </summary>
        public static string Options_json_is_not_empty__Overwrite {
            get {
                return ResourceManager.GetString("Options_json_is_not_empty__Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait for generating files....
        /// </summary>
        public static string Please_wait_for_generating_files {
            get {
                return ResourceManager.GetString("Please_wait_for_generating_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait for the code dependencies scanning....
        /// </summary>
        public static string Please_wait_for_the_code_dependencies {
            get {
                return ResourceManager.GetString("Please_wait_for_the_code_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press # to enter context items here. Press Ctrl + Enter to add items to context..
        /// </summary>
        public static string Press___to_enter_context_items_here {
            get {
                return ResourceManager.GetString("Press___to_enter_context_items_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process SUCESSFULLY completed.
        /// </summary>
        public static string Process_SUCESSFULLY_completed {
            get {
                return ResourceManager.GetString("Process_SUCESSFULLY_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt:.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Re)write NLO json file completely....
        /// </summary>
        public static string Re_write_NLO_json_file_completely {
            get {
                return ResourceManager.GetString("Re_write_NLO_json_file_completely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading answer.
        /// </summary>
        public static string Reading_answer {
            get {
                return ResourceManager.GetString("Reading_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove all automatic found items.
        /// </summary>
        public static string Remove_all_automatic_found_items {
            get {
                return ResourceManager.GetString("Remove all automatic found items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove all automatic found items from chat context.
        /// </summary>
        public static string Remove_all_automatic_found_items_from_chat_context {
            get {
                return ResourceManager.GetString("Remove all automatic found items from chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace the selected block of the code in the VS document with this code part.
        /// </summary>
        public static string Replace_the_selected_block_of_the {
            get {
                return ResourceManager.GetString("Replace_the_selected_block_of_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace this system prompt with default system prompt of general purpose.
        /// </summary>
        public static string Replace_this_system_prompt_with_default {
            get {
                return ResourceManager.GetString("Replace_this_system_prompt_with_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace with general system prompt....
        /// </summary>
        public static string Replace_with_general_system_prompt {
            get {
                return ResourceManager.GetString("Replace_with_general_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search and add related context items (.NET only).
        /// </summary>
        public static string Search_and_add_related_context_items {
            get {
                return ResourceManager.GetString("Search_and_add_related_context_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show only user chats.
        /// </summary>
        public static string Show_only_user_chats {
            get {
                return ResourceManager.GetString("Show only user chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some tasks are in progress.
        /// </summary>
        public static string Some_tasks_are_in_progress {
            get {
                return ResourceManager.GetString("Some_tasks_are_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start discussion.
        /// </summary>
        public static string Start_discussion {
            get {
                return ResourceManager.GetString("Start_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start embedding generation.
        /// </summary>
        public static string Start_embedding_generation {
            get {
                return ResourceManager.GetString("Start_embedding_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start NLO extraction....
        /// </summary>
        public static string Start_NLO_extraction {
            get {
                return ResourceManager.GetString("Start_NLO_extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start process to actualize NLO Json file. Log of the process is in Visual Studio output pane.
        /// </summary>
        public static string Start_process_to_actualize_NLO_Json_file {
            get {
                return ResourceManager.GetString("Start process to actualize NLO Json file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status is unknown.
        /// </summary>
        public static string Status_is_unknown {
            get {
                return ResourceManager.GetString("Status_is_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This item came from software logic.
        /// </summary>
        public static string This_item_came_from_software_logic {
            get {
                return ResourceManager.GetString("This_item_came_from_software_logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This item came from user.
        /// </summary>
        public static string This_item_came_from_user {
            get {
                return ResourceManager.GetString("This_item_came_from_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token:.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer.
        /// </summary>
        public static string UI_Answer {
            get {
                return ResourceManager.GetString("UI_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        public static string UI_Choose {
            get {
                return ResourceManager.GetString("UI_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete rebuild.
        /// </summary>
        public static string UI_CompleteRebuild {
            get {
                return ResourceManager.GetString("UI_CompleteRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load only free models.
        /// </summary>
        public static string UI_LoadOnlyFreeModels {
            get {
                return ResourceManager.GetString("UI_LoadOnlyFreeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in main editor....
        /// </summary>
        public static string UI_OpenInEditor {
            get {
                return ResourceManager.GetString("UI_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt.
        /// </summary>
        public static string UI_Prompt {
            get {
                return ResourceManager.GetString("UI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove chat.
        /// </summary>
        public static string UI_RemoveChat {
            get {
                return ResourceManager.GetString("UI_RemoveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start chat....
        /// </summary>
        public static string UI_StartDiscussion {
            get {
                return ResourceManager.GetString("UI_StartDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string UI_StopWaiting {
            get {
                return ResourceManager.GetString("UI_StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update page....
        /// </summary>
        public static string UI_UpdatePage {
            get {
                return ResourceManager.GetString("UI_UpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown error occurred during scanning for dependencies.
        /// </summary>
        public static string Unknown_error_occurred_during_scanning {
            get {
                return ResourceManager.GetString("Unknown_error_occurred_during_scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update NLO json file....
        /// </summary>
        public static string Update_NLO_json_file {
            get {
                return ResourceManager.GetString("Update_NLO_json_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visual studio has no active FreeAIr options..
        /// </summary>
        public static string Visual_studio_has_no_active_FreeAIr {
            get {
                return ResourceManager.GetString("Visual_studio_has_no_active_FreeAIr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for answer.
        /// </summary>
        public static string Waiting_for_answer {
            get {
                return ResourceManager.GetString("Waiting_for_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for status.
        /// </summary>
        public static string Waiting_for_status {
            get {
                return ResourceManager.GetString("Waiting_for_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are going to delete stored options. Please, confirm..
        /// </summary>
        public static string You_are_going_to_delete_stored_options {
            get {
                return ResourceManager.GetString("You_are_going_to_delete_stored_options", resourceCulture);
            }
        }
    }
}
