//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAIr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeAIr.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain selected block of code..
        /// </summary>
        public static string Code_NoSelectedCode {
            get {
                return ResourceManager.GetString("Code_NoSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup API endpoint and access token in FreeAIr control panel. If you are using local LLM enter any string into token option..
        /// </summary>
        public static string Code_NoToken {
            get {
                return ResourceManager.GetString("Code_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string UI_Answer {
            get {
                return ResourceManager.GetString("UI_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string UI_Choose {
            get {
                return ResourceManager.GetString("UI_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load only free models.
        /// </summary>
        public static string UI_LoadOnlyFreeModels {
            get {
                return ResourceManager.GetString("UI_LoadOnlyFreeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in main editor....
        /// </summary>
        public static string UI_OpenInEditor {
            get {
                return ResourceManager.GetString("UI_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string UI_Prompt {
            get {
                return ResourceManager.GetString("UI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove chat.
        /// </summary>
        public static string UI_RemoveChat {
            get {
                return ResourceManager.GetString("UI_RemoveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat....
        /// </summary>
        public static string UI_StartDiscussion {
            get {
                return ResourceManager.GetString("UI_StartDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string UI_StopWaiting {
            get {
                return ResourceManager.GetString("UI_StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page....
        /// </summary>
        public static string UI_UpdatePage {
            get {
                return ResourceManager.GetString("UI_UpdatePage", resourceCulture);
            }
        }
    }
}
