//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAIr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeAIr.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom file....
        /// </summary>
        public static string Add_custom_file {
            get {
                return ResourceManager.GetString("Add custom file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI chat list.
        /// </summary>
        public static string AI_chat_list {
            get {
                return ResourceManager.GetString("AI chat list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI is getting colder, it nothing is asked about.
        /// </summary>
        public static string AI_is_getting_colder {
            get {
                return ResourceManager.GetString("AI_is_getting_colder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Natural Language Outlines Json File.
        /// </summary>
        public static string Build_Natural_Language_Outlines_Json_File {
            get {
                return ResourceManager.GetString("Build_Natural_Language_Outlines_Json_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat context:.
        /// </summary>
        public static string Chat_context {
            get {
                return ResourceManager.GetString("Chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this chat agent. These changes are not shared across other chats..
        /// </summary>
        public static string Choose_this_chat_agent {
            get {
                return ResourceManager.GetString("Choose this chat agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain selected block of code..
        /// </summary>
        public static string Code_NoSelectedCode {
            get {
                return ResourceManager.GetString("Code_NoSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup API endpoint and access token in FreeAIr control panel. If you are using local LLM enter any string into token option..
        /// </summary>
        public static string Code_NoToken {
            get {
                return ResourceManager.GetString("Code_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from context.
        /// </summary>
        public static string Delete_from_context {
            get {
                return ResourceManager.GetString("Delete from context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit chat tools....
        /// </summary>
        public static string Edit_chat_tools {
            get {
                return ResourceManager.GetString("Edit chat tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FreeAIr options. Changes that made do not affects your opened chats..
        /// </summary>
        public static string Edit_FreeAIr_options {
            get {
                return ResourceManager.GetString("Edit_FreeAIr_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the MCP tools for the selected chat. These changes are not shared across other chats..
        /// </summary>
        public static string Edit_the_MCP_tools_for_the_selected_chat {
            get {
                return ResourceManager.GetString("Edit the MCP tools for the selected chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding generate agent:.
        /// </summary>
        public static string Embedding_generate_agent {
            get {
                return ResourceManager.GetString("Embedding generate agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force use chosen NLO agent.
        /// </summary>
        public static string Force_use_chosen_NLO_agent {
            get {
                return ResourceManager.GetString("Force_use_chosen_NLO_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr available support.
        /// </summary>
        public static string FreeAIr_available_support {
            get {
                return ResourceManager.GetString("FreeAIr_available_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its prompt template.
        /// </summary>
        public static string Its_prompt_template {
            get {
                return ResourceManager.GetString("Its_prompt_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Language Outlines file path.
        /// </summary>
        public static string Natural_Language_Outlines_file_path {
            get {
                return ResourceManager.GetString("Natural_Language_Outlines_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLO extract action:.
        /// </summary>
        public static string NLO_extract_action {
            get {
                return ResourceManager.GetString("NLO extract action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLO extract agent:.
        /// </summary>
        public static string NLO_extract_agent {
            get {
                return ResourceManager.GetString("NLO extract agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NLO embedding file(s) path depends on solution name. These files are useful for natural language search feature of FreeAIr. FreeAIr will use these embeddings to narrow down the search scope. It is recommended to actualize these files before every commit to keep embeddings in sync with your codebase..
        /// </summary>
        public static string NLOG_Tooltip10 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Checked tree items will be updated with a new embeddings, unchecked items will reuse the existing embeddings..
        /// </summary>
        public static string NLOG_Tooltip20 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FreeAIr process C# files with Roslyn, for any other file &apos;NLO extract agent&apos; is used. This is an agent to extract natural language outlines from a source file if FreeAIr does not know its syntax tree and cannot extract NLOs from its body natively. If you choose &apos;Force use chosen NLO agent&apos; then selected agent will be used for every processed file..
        /// </summary>
        public static string NLOG_Tooltip30 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;Embedding generate agent&apos; is an agent to generate the embeddings from gathered natural language outlines..
        /// </summary>
        public static string NLOG_Tooltip40 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Natural language outlines are used to apply RAG (retrieval augmented generation) for natural language search, and based on the paper https://arxiv.org/html/2408.04820v4.
        /// </summary>
        public static string NLOG_Tooltip50 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Not_started {
            get {
                return ResourceManager.GetString("Not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open contol center....
        /// </summary>
        public static string Open_contol_center {
            get {
                return ResourceManager.GetString("Open contol center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all automatic found items.
        /// </summary>
        public static string Remove_all_automatic_found_items {
            get {
                return ResourceManager.GetString("Remove all automatic found items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all automatic found items from chat context.
        /// </summary>
        public static string Remove_all_automatic_found_items_from_chat_context {
            get {
                return ResourceManager.GetString("Remove all automatic found items from chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only user chats.
        /// </summary>
        public static string Show_only_user_chats {
            get {
                return ResourceManager.GetString("Show only user chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some tasks are in progress.
        /// </summary>
        public static string Some_tasks_are_in_progress {
            get {
                return ResourceManager.GetString("Some_tasks_are_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start discussion.
        /// </summary>
        public static string Start_discussion {
            get {
                return ResourceManager.GetString("Start_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start process to actualize NLO Json file. Log of the process is in Visual Studio output pane.
        /// </summary>
        public static string Start_process_to_actualize_NLO_Json_file {
            get {
                return ResourceManager.GetString("Start process to actualize NLO Json file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is unknown.
        /// </summary>
        public static string Status_is_unknown {
            get {
                return ResourceManager.GetString("Status_is_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string UI_Answer {
            get {
                return ResourceManager.GetString("UI_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string UI_Choose {
            get {
                return ResourceManager.GetString("UI_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete rebuild.
        /// </summary>
        public static string UI_CompleteRebuild {
            get {
                return ResourceManager.GetString("UI_CompleteRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load only free models.
        /// </summary>
        public static string UI_LoadOnlyFreeModels {
            get {
                return ResourceManager.GetString("UI_LoadOnlyFreeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in main editor....
        /// </summary>
        public static string UI_OpenInEditor {
            get {
                return ResourceManager.GetString("UI_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string UI_Prompt {
            get {
                return ResourceManager.GetString("UI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove chat.
        /// </summary>
        public static string UI_RemoveChat {
            get {
                return ResourceManager.GetString("UI_RemoveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat....
        /// </summary>
        public static string UI_StartDiscussion {
            get {
                return ResourceManager.GetString("UI_StartDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string UI_StopWaiting {
            get {
                return ResourceManager.GetString("UI_StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page....
        /// </summary>
        public static string UI_UpdatePage {
            get {
                return ResourceManager.GetString("UI_UpdatePage", resourceCulture);
            }
        }
    }
}
