//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAIr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeAIr.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Inside your Visual Studio (developer-related approach)..
        /// </summary>
        public static string a_2__Inside_your_Visual_Studio__developer {
            get {
                return ResourceManager.GetString("a_2__Inside_your_Visual_Studio__developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom file....
        /// </summary>
        public static string Add_custom_file {
            get {
                return ResourceManager.GetString("Add custom file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom file to chat context.
        /// </summary>
        public static string Add_custom_file_to_chat_context {
            get {
                return ResourceManager.GetString("Add_custom_file_to_chat_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string Add_new {
            get {
                return ResourceManager.GetString("Add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new action.
        /// </summary>
        public static string Add_new_action {
            get {
                return ResourceManager.GetString("Add_new_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new agent.
        /// </summary>
        public static string Add_new_agent {
            get {
                return ResourceManager.GetString("Add_new_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new items to context.
        /// </summary>
        public static string Add_new_items_to_context {
            get {
                return ResourceManager.GetString("Add_new_items_to_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new items to context:.
        /// </summary>
        public static string Add_new_items_to_context1 {
            get {
                return ResourceManager.GetString("Add_new_items_to_context1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent name.
        /// </summary>
        public static string Agent_name {
            get {
                return ResourceManager.GetString("Agent_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent system prompt:.
        /// </summary>
        public static string Agent_system_prompt {
            get {
                return ResourceManager.GetString("Agent_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI chat list.
        /// </summary>
        public static string AI_chat_list {
            get {
                return ResourceManager.GetString("AI chat list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI is getting colder, it nothing is asked about.
        /// </summary>
        public static string AI_is_getting_colder {
            get {
                return ResourceManager.GetString("AI_is_getting_colder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        public static string Apply_changes {
            get {
                return ResourceManager.GetString("Apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available agents:.
        /// </summary>
        public static string Available_agents {
            get {
                return ResourceManager.GetString("Available_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Natural Language Outlines Json File.
        /// </summary>
        public static string Build_Natural_Language_Outlines_Json_File {
            get {
                return ResourceManager.GetString("Build_Natural_Language_Outlines_Json_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel chat.
        /// </summary>
        public static string Cancel_chat {
            get {
                return ResourceManager.GetString("Cancel_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot collect git patch..
        /// </summary>
        public static string Cannot_collect_git_patch {
            get {
                return ResourceManager.GetString("Cannot_collect_git_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot collect git patch. Please enter commit message manually..
        /// </summary>
        public static string Cannot_collect_git_patch__Please {
            get {
                return ResourceManager.GetString("Cannot_collect_git_patch__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new file. Please create the file manually..
        /// </summary>
        public static string Cannot_create_a_new_file__Please {
            get {
                return ResourceManager.GetString("Cannot_create_a_new_file__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine git repository path..
        /// </summary>
        public static string Cannot_determine_git_repository_path {
            get {
                return ResourceManager.GetString("Cannot_determine_git_repository_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the position of found entry. The file will be open without selection..
        /// </summary>
        public static string Cannot_determine_the_position_of {
            get {
                return ResourceManager.GetString("Cannot_determine_the_position_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit the document. Please copy-paste the text manually..
        /// </summary>
        public static string Cannot_edit_the_document__Please {
            get {
                return ResourceManager.GetString("Cannot_edit_the_document__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot receive LLM answer. Please enter commit message manually..
        /// </summary>
        public static string Cannot_receive_AI_answer__Please {
            get {
                return ResourceManager.GetString("Cannot_receive_AI_answer__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace context document body. Please replace manually..
        /// </summary>
        public static string Cannot_replace_context_document_body {
            get {
                return ResourceManager.GetString("Cannot_replace_context_document_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace selected text. Please replace the selected text manually..
        /// </summary>
        public static string Cannot_replace_selected_text__Please {
            get {
                return ResourceManager.GetString("Cannot_replace_selected_text__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat context:.
        /// </summary>
        public static string Chat_context {
            get {
                return ResourceManager.GetString("Chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for connection....
        /// </summary>
        public static string Check_for_connection {
            get {
                return ResourceManager.GetString("Check_for_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose agent (with a non-empty token) for a chat:.
        /// </summary>
        public static string Choose_agent__with_a_non_empty_token {
            get {
                return ResourceManager.GetString("Choose_agent__with_a_non_empty_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose agent for commit message generation:.
        /// </summary>
        public static string Choose_agent_for_commit_message_generation {
            get {
                return ResourceManager.GetString("Choose_agent_for_commit_message_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose agent for natural language search:.
        /// </summary>
        public static string Choose_agent_for_natural_language {
            get {
                return ResourceManager.GetString("Choose_agent_for_natural_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose agent to add NL outlines to changed files:.
        /// </summary>
        public static string Choose_agent_to_add_NL_outlines_to {
            get {
                return ResourceManager.GetString("Choose_agent_to_add_NL_outlines_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose chat agent{0}....
        /// </summary>
        public static string Choose_chat_agent {
            get {
                return ResourceManager.GetString("Choose_chat_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose context item to replace:.
        /// </summary>
        public static string Choose_context_item_to_replace {
            get {
                return ResourceManager.GetString("Choose_context_item_to_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose context item to replace its content with this code part.
        /// </summary>
        public static string Choose_context_item_to_replace_its {
            get {
                return ResourceManager.GetString("Choose_context_item_to_replace_its", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose model from this api endpoint.
        /// </summary>
        public static string Choose_model_from_this_api_endpoint {
            get {
                return ResourceManager.GetString("Choose_model_from_this_api_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose OpenRouter model.
        /// </summary>
        public static string Choose_OpenRouter_model {
            get {
                return ResourceManager.GetString("Choose_OpenRouter_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose searching scope:.
        /// </summary>
        public static string Choose_searching_scope {
            get {
                return ResourceManager.GetString("Choose_searching_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose support action:.
        /// </summary>
        public static string Choose_support_action {
            get {
                return ResourceManager.GetString("Choose_support_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the available agent:.
        /// </summary>
        public static string Choose_the_available_agent {
            get {
                return ResourceManager.GetString("Choose_the_available_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the MCP tools you want to provide to LLM:.
        /// </summary>
        public static string Choose_the_MCP_tools_you_want_to {
            get {
                return ResourceManager.GetString("Choose_the_MCP_tools_you_want_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this chat agent. These changes are not shared across other chats..
        /// </summary>
        public static string Choose_this_chat_agent {
            get {
                return ResourceManager.GetString("Choose this chat agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (chosen).
        /// </summary>
        public static string chosen {
            get {
                return ResourceManager.GetString("chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen model:.
        /// </summary>
        public static string Chosen_model {
            get {
                return ResourceManager.GetString("Chosen_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy to clipboard.
        /// </summary>
        public static string Click_to_copy_to_clipboard {
            get {
                return ResourceManager.GetString("Click_to_copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (cloned).
        /// </summary>
        public static string cloned {
            get {
                return ResourceManager.GetString("cloned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain selected block of code..
        /// </summary>
        public static string Code_NoSelectedCode {
            get {
                return ResourceManager.GetString("Code_NoSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup API endpoint and access token in FreeAIr control panel. If you are using local LLM enter any string into token option..
        /// </summary>
        public static string Code_NoToken {
            get {
                return ResourceManager.GetString("Code_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented Line.
        /// </summary>
        public static string Commented_Line {
            get {
                return ResourceManager.GetString("Commented_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        public static string Confidence {
            get {
                return ResourceManager.GetString("Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context size:.
        /// </summary>
        public static string Context_size {
            get {
                return ResourceManager.GetString("Context_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file with this code part.
        /// </summary>
        public static string Create_new_file_with_this_code_part {
            get {
                return ResourceManager.GetString("Create_new_file_with_this_code_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current json is different from the saved one. Consider saving your changes..
        /// </summary>
        public static string Current_json_is_different_from_the {
            get {
                return ResourceManager.GetString("Current_json_is_different_from_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project.
        /// </summary>
        public static string Current_project {
            get {
                return ResourceManager.GetString("Current_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from context.
        /// </summary>
        public static string Delete_from_context {
            get {
                return ResourceManager.GetString("Delete from context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Delete_selected {
            get {
                return ResourceManager.GetString("Delete_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected action.
        /// </summary>
        public static string Delete_selected_action {
            get {
                return ResourceManager.GetString("Delete_selected_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected agent.
        /// </summary>
        public static string Delete_selected_agent {
            get {
                return ResourceManager.GetString("Delete_selected_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker image for {0} MCP server installed. Please setup FreeAIr to work with the server..
        /// </summary>
        public static string Docker_image_for__0__MCP_server_installed {
            get {
                return ResourceManager.GetString("Docker_image_for__0__MCP_server_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit actions....
        /// </summary>
        public static string Edit_actions {
            get {
                return ResourceManager.GetString("Edit_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit agents....
        /// </summary>
        public static string Edit_agents {
            get {
                return ResourceManager.GetString("Edit_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit chat tools....
        /// </summary>
        public static string Edit_chat_tools {
            get {
                return ResourceManager.GetString("Edit chat tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FreeAIr options. Changes that made do not affects your opened chats..
        /// </summary>
        public static string Edit_FreeAIr_options {
            get {
                return ResourceManager.GetString("Edit_FreeAIr_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit global MCP tools....
        /// </summary>
        public static string Edit_global_MCP_tools {
            get {
                return ResourceManager.GetString("Edit_global_MCP_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit MCP servers....
        /// </summary>
        public static string Edit_MCP_servers {
            get {
                return ResourceManager.GetString("Edit_MCP_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the MCP tools for the selected chat. These changes are not shared across other chats..
        /// </summary>
        public static string Edit_the_MCP_tools_for_the_selected_chat {
            get {
                return ResourceManager.GetString("Edit the MCP tools for the selected chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding generate agent:.
        /// </summary>
        public static string Embedding_generate_agent {
            get {
                return ResourceManager.GetString("Embedding generate agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint:.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your prompt here. Press / to open commands. Press # to choose solution item. Press Ctrl + Enter to send your prompt..
        /// </summary>
        public static string Enter_your_prompt_here__Press___to {
            get {
                return ResourceManager.GetString("Enter_your_prompt_here__Press___to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string Error_occurred {
            get {
                return ResourceManager.GetString("Error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every MCP server is found, and pinged successfully. Changes was saved successfully..
        /// </summary>
        public static string Every_MCP_server_is_found__and_pinged {
            get {
                return ResourceManager.GetString("Every_MCP_server_is_found__and_pinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find using natural language.
        /// </summary>
        public static string Find_using_natural_language {
            get {
                return ResourceManager.GetString("Find_using_natural_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find using natural language in current solution or the current project.
        /// </summary>
        public static string Find_using_natural_language_in_current {
            get {
                return ResourceManager.GetString("Find_using_natural_language_in_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exists yet. Save NLO Json file to create the folder..
        /// </summary>
        public static string Folder_does_not_exists_yet__Save {
            get {
                return ResourceManager.GetString("Folder_does_not_exists_yet__Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force use chosen NLO agent.
        /// </summary>
        public static string Force_use_chosen_NLO_agent {
            get {
                return ResourceManager.GetString("Force_use_chosen_NLO_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found text.
        /// </summary>
        public static string Found_text {
            get {
                return ResourceManager.GetString("Found_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr Agent Configuration Window.
        /// </summary>
        public static string FreeAIr_Agent_Configuration_Window {
            get {
                return ResourceManager.GetString("FreeAIr_Agent_Configuration_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr available support.
        /// </summary>
        public static string FreeAIr_available_support {
            get {
                return ResourceManager.GetString("FreeAIr_available_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr Control Center.
        /// </summary>
        public static string FreeAIr_Control_Center {
            get {
                return ResourceManager.GetString("FreeAIr_Control_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr MCP Servers Configuration Window.
        /// </summary>
        public static string FreeAIr_MCP_Servers_Configuration {
            get {
                return ResourceManager.GetString("FreeAIr_MCP_Servers_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr Natural Language Outlines.
        /// </summary>
        public static string FreeAIr_Natural_Language_Outlines {
            get {
                return ResourceManager.GetString("FreeAIr_Natural_Language_Outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr NLO Json file generation.
        /// </summary>
        public static string FreeAIr_NLO_Json_file_generation {
            get {
                return ResourceManager.GetString("FreeAIr_NLO_Json_file_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FreeAIr options can be saved into 2 locations:.
        /// </summary>
        public static string FreeAIr_options_can_be_saved_into {
            get {
                return ResourceManager.GetString("FreeAIr_options_can_be_saved_into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr options file does not found.
        /// </summary>
        public static string FreeAIr_options_file_does_not_found {
            get {
                return ResourceManager.GetString("FreeAIr_options_file_does_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr support: build natural language outlines json file related to the diff below..
        /// </summary>
        public static string FreeAIr_support__build_natural_language {
            get {
                return ResourceManager.GetString("FreeAIr_support__build_natural_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr support: generate and add natural language outlines related to the diff below..
        /// </summary>
        public static string FreeAIr_support__generate_and_add {
            get {
                return ResourceManager.GetString("FreeAIr_support__generate_and_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr support: generate commit message.
        /// </summary>
        public static string FreeAIr_support__generate_commit {
            get {
                return ResourceManager.GetString("FreeAIr_support__generate_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeAIr Support Action Configuration Window.
        /// </summary>
        public static string FreeAIr_Support_Action_Configuration {
            get {
                return ResourceManager.GetString("FreeAIr_Support_Action_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated {0} comments:.
        /// </summary>
        public static string Generated__0__comments {
            get {
                return ResourceManager.GetString("Generated__0__comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub MCP server installed SUCCESSFULLY..
        /// </summary>
        public static string GitHub_MCP_server_installed_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("GitHub_MCP_server_installed_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github MCP Server status:.
        /// </summary>
        public static string Github_MCP_Server_status {
            get {
                return ResourceManager.GetString("Github_MCP_Server_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you have both (json file and VS options) FreeAIr will use json file options. If you have nothing FreeAIr will use the default (embedded) options, which are useless for chat with LLM..
        /// </summary>
        public static string If_you_have_both__json_file_and {
            get {
                return ResourceManager.GetString("If_you_have_both__json_file_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress ({0}/{1})....
        /// </summary>
        public static string In_progress___0___1 {
            get {
                return ResourceManager.GetString("In_progress___0___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and setup....
        /// </summary>
        public static string Install_and_setup {
            get {
                return ResourceManager.GetString("Install_and_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Github MCP server....
        /// </summary>
        public static string Install_Github_MCP_server {
            get {
                return ResourceManager.GetString("Install_Github_MCP_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation GitHub MCP server fails. Please install it manually..
        /// </summary>
        public static string Installation_GitHub_MCP_server_fails {
            get {
                return ResourceManager.GetString("Installation_GitHub_MCP_server_fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed and Ready.
        /// </summary>
        public static string Installed_and_Ready {
            get {
                return ResourceManager.GetString("Installed_and_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid json. Fix json and try again..
        /// </summary>
        public static string Invalid_json__Fix_json_and_try_again {
            get {
                return ResourceManager.GetString("Invalid_json__Fix_json_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its prompt template.
        /// </summary>
        public static string Its_prompt_template {
            get {
                return ResourceManager.GetString("Its_prompt_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json cannot be deserialized because of:.
        /// </summary>
        public static string Json_cannot_be_deserialized_because {
            get {
                return ResourceManager.GetString("Json_cannot_be_deserialized_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Json file on the disk (solution-related approach)..
        /// </summary>
        public static string Json_file__solution_related_approach {
            get {
                return ResourceManager.GetString("Json_file__solution_related_approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Json file is placed in the folder of your solution + &apos;.freeair&apos; folder + &apos;your_solution_name&gt;_options.json&apos; filename. This file is a subject of committing to the git repo. This is useful for a command working, when every member of the team can use the same FreeAIr options, for example, connection to the company&apos;s LLM..
        /// </summary>
        public static string Json_file_is_placed_in_the_folder {
            get {
                return ResourceManager.GetString("Json_file_is_placed_in_the_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server is found, and pinged successfully..
        /// </summary>
        public static string MCP_server_is_found__and_pinged_successfully {
            get {
                return ResourceManager.GetString("MCP_server_is_found__and_pinged_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP servers did not respond. Save options anyway?.
        /// </summary>
        public static string MCP_servers_did_not_respond__Save {
            get {
                return ResourceManager.GetString("MCP_servers_did_not_respond__Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model list cannot be loaded.
        /// </summary>
        public static string Model_list_cannot_be_loaded {
            get {
                return ResourceManager.GetString("Model_list_cannot_be_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model list is loading....
        /// </summary>
        public static string Model_list_is_loading {
            get {
                return ResourceManager.GetString("Model_list_is_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected action down.
        /// </summary>
        public static string Move_selected_action_down {
            get {
                return ResourceManager.GetString("Move_selected_action_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected action up.
        /// </summary>
        public static string Move_selected_action_up {
            get {
                return ResourceManager.GetString("Move_selected_action_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected agent down.
        /// </summary>
        public static string Move_selected_agent_down {
            get {
                return ResourceManager.GetString("Move_selected_agent_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected agent up.
        /// </summary>
        public static string Move_selected_agent_up {
            get {
                return ResourceManager.GetString("Move_selected_agent_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected down.
        /// </summary>
        public static string Move_selected_down {
            get {
                return ResourceManager.GetString("Move_selected_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected up.
        /// </summary>
        public static string Move_selected_up {
            get {
                return ResourceManager.GetString("Move_selected_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Language Outlines file path.
        /// </summary>
        public static string Natural_Language_Outlines_file_path {
            get {
                return ResourceManager.GetString("Natural_Language_Outlines_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural language search results.
        /// </summary>
        public static string Natural_language_search_results {
            get {
                return ResourceManager.GetString("Natural_language_search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of FreeAIr has been installed..
        /// </summary>
        public static string New_version_of_FreeAIr_has_been_installed {
            get {
                return ResourceManager.GetString("New_version_of_FreeAIr_has_been_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLO extract action:.
        /// </summary>
        public static string NLO_extract_action {
            get {
                return ResourceManager.GetString("NLO extract action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLO extract agent:.
        /// </summary>
        public static string NLO_extract_agent {
            get {
                return ResourceManager.GetString("NLO extract agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NLO embedding file(s) path depends on solution name. These files are useful for natural language search feature of FreeAIr. FreeAIr will use these embeddings to narrow down the search scope. It is recommended to actualize these files before every commit to keep embeddings in sync with your codebase..
        /// </summary>
        public static string NLOG_Tooltip10 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Checked tree items will be updated with a new embeddings, unchecked items will reuse the existing embeddings..
        /// </summary>
        public static string NLOG_Tooltip20 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FreeAIr process C# files with Roslyn, for any other file &apos;NLO extract agent&apos; is used. This is an agent to extract natural language outlines from a source file if FreeAIr does not know its syntax tree and cannot extract NLOs from its body natively. If you choose &apos;Force use chosen NLO agent&apos; then selected agent will be used for every processed file..
        /// </summary>
        public static string NLOG_Tooltip30 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;Embedding generate agent&apos; is an agent to generate the embeddings from gathered natural language outlines..
        /// </summary>
        public static string NLOG_Tooltip40 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Natural language outlines are used to apply RAG (retrieval augmented generation) for natural language search, and based on the paper https://arxiv.org/html/2408.04820v4.
        /// </summary>
        public static string NLOG_Tooltip50 {
            get {
                return ResourceManager.GetString("NLOG_Tooltip50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments applied.
        /// </summary>
        public static string No_comments_applied {
            get {
                return ResourceManager.GetString("No_comments_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments for the file {0} applied.
        /// </summary>
        public static string No_comments_for_file__0__applied {
            get {
                return ResourceManager.GetString("No_comments_for_file__0__applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dependencies found. This may occurs because Intellisense is not loaded (yet), or the context item is not a .Net source code..
        /// </summary>
        public static string No_dependencies_found__This_may_occurs {
            get {
                return ResourceManager.GetString("No_dependencies_found__This_may_occurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string Not_Installed {
            get {
                return ResourceManager.GetString("Not_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not interested.
        /// </summary>
        public static string Not_interested {
            get {
                return ResourceManager.GetString("Not_interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Not_started {
            get {
                return ResourceManager.GetString("Not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open contol center....
        /// </summary>
        public static string Open_contol_center {
            get {
                return ResourceManager.GetString("Open contol center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser....
        /// </summary>
        public static string Open_in_browser {
            get {
                return ResourceManager.GetString("Open_in_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open item in new window.
        /// </summary>
        public static string Open_item_in_new_window {
            get {
                return ResourceManager.GetString("Open_item_in_new_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options file {0} has been deleted..
        /// </summary>
        public static string Options_file__0__has_been_deleted {
            get {
                return ResourceManager.GetString("Options_file__0__has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options inside Visual Studio has been deleted..
        /// </summary>
        public static string Options_inside_Visual_Studio_has {
            get {
                return ResourceManager.GetString("Options_inside_Visual_Studio_has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options json is not empty. Overwrite?.
        /// </summary>
        public static string Options_json_is_not_empty__Overwrite {
            get {
                return ResourceManager.GetString("Options_json_is_not_empty__Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for generating files....
        /// </summary>
        public static string Please_wait_for_generating_files {
            get {
                return ResourceManager.GetString("Please_wait_for_generating_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for git patch building....
        /// </summary>
        public static string Please_wait_for_git_patch_building {
            get {
                return ResourceManager.GetString("Please_wait_for_git_patch_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the code dependencies scanning....
        /// </summary>
        public static string Please_wait_for_the_code_dependencies {
            get {
                return ResourceManager.GetString("Please_wait_for_the_code_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press # to enter context items here. Press Ctrl + Enter to add items to context..
        /// </summary>
        public static string Press___to_enter_context_items_here {
            get {
                return ResourceManager.GetString("Press___to_enter_context_items_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process SUCESSFULLY completed.
        /// </summary>
        public static string Process_SUCESSFULLY_completed {
            get {
                return ResourceManager.GetString("Process_SUCESSFULLY_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt:.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Re)write NLO json file completely....
        /// </summary>
        public static string Re_write_NLO_json_file_completely {
            get {
                return ResourceManager.GetString("Re_write_NLO_json_file_completely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading answer.
        /// </summary>
        public static string Reading_answer {
            get {
                return ResourceManager.GetString("Reading_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all automatic found items.
        /// </summary>
        public static string Remove_all_automatic_found_items {
            get {
                return ResourceManager.GetString("Remove all automatic found items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all automatic found items from chat context.
        /// </summary>
        public static string Remove_all_automatic_found_items_from_chat_context {
            get {
                return ResourceManager.GetString("Remove all automatic found items from chat context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the selected block of the code in the VS document with this code part.
        /// </summary>
        public static string Replace_the_selected_block_of_the {
            get {
                return ResourceManager.GetString("Replace_the_selected_block_of_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this system prompt with default system prompt of general purpose.
        /// </summary>
        public static string Replace_this_system_prompt_with_default {
            get {
                return ResourceManager.GetString("Replace_this_system_prompt_with_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this system prompt with default system prompt of generate new or update existing natural language outlines.
        /// </summary>
        public static string Replace_this_system_prompt_with_default_NLO_g {
            get {
                return ResourceManager.GetString("Replace_this_system_prompt_with_default_NLO_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this system prompt with default system prompt of extract natural language outlines from documents..
        /// </summary>
        public static string Replace_this_system_prompt_with_default_NLO_s {
            get {
                return ResourceManager.GetString("Replace_this_system_prompt_with_default_NLO_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with extract NLO system prompt....
        /// </summary>
        public static string Replace_with_extract_NLO_system_prompt {
            get {
                return ResourceManager.GetString("Replace_with_extract_NLO_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with general system prompt....
        /// </summary>
        public static string Replace_with_general_system_prompt {
            get {
                return ResourceManager.GetString("Replace_with_general_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with generate NLO system prompt....
        /// </summary>
        public static string Replace_with_generate_NLO_system {
            get {
                return ResourceManager.GetString("Replace_with_generate_NLO_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and add related context items (.NET only).
        /// </summary>
        public static string Search_and_add_related_context_items {
            get {
                return ResourceManager.GetString("Search_and_add_related_context_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for MCP servers in Docker registry....
        /// </summary>
        public static string Search_for_MCP_servers_in_Docker {
            get {
                return ResourceManager.GetString("Search_for_MCP_servers_in_Docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only user chats.
        /// </summary>
        public static string Show_only_user_chats {
            get {
                return ResourceManager.GetString("Show only user chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show release notes.
        /// </summary>
        public static string Show_release_notes {
            get {
                return ResourceManager.GetString("Show_release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some tasks are in progress.
        /// </summary>
        public static string Some_tasks_are_in_progress {
            get {
                return ResourceManager.GetString("Some_tasks_are_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start discussion.
        /// </summary>
        public static string Start_discussion {
            get {
                return ResourceManager.GetString("Start_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start embedding generation.
        /// </summary>
        public static string Start_embedding_generation {
            get {
                return ResourceManager.GetString("Start_embedding_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start NLO extraction....
        /// </summary>
        public static string Start_NLO_extraction {
            get {
                return ResourceManager.GetString("Start_NLO_extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start process to actualize NLO Json file. Log of the process is in Visual Studio output pane.
        /// </summary>
        public static string Start_process_to_actualize_NLO_Json_file {
            get {
                return ResourceManager.GetString("Start process to actualize NLO Json file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is unknown.
        /// </summary>
        public static string Status_is_unknown {
            get {
                return ResourceManager.GetString("Status_is_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item came from software logic.
        /// </summary>
        public static string This_item_came_from_software_logic {
            get {
                return ResourceManager.GetString("This_item_came_from_software_logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item came from user.
        /// </summary>
        public static string This_item_came_from_user {
            get {
                return ResourceManager.GetString("This_item_came_from_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token:.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string UI_Answer {
            get {
                return ResourceManager.GetString("UI_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string UI_Choose {
            get {
                return ResourceManager.GetString("UI_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete rebuild.
        /// </summary>
        public static string UI_CompleteRebuild {
            get {
                return ResourceManager.GetString("UI_CompleteRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load only free models.
        /// </summary>
        public static string UI_LoadOnlyFreeModels {
            get {
                return ResourceManager.GetString("UI_LoadOnlyFreeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in main editor....
        /// </summary>
        public static string UI_OpenInEditor {
            get {
                return ResourceManager.GetString("UI_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string UI_Prompt {
            get {
                return ResourceManager.GetString("UI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove chat.
        /// </summary>
        public static string UI_RemoveChat {
            get {
                return ResourceManager.GetString("UI_RemoveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat....
        /// </summary>
        public static string UI_StartDiscussion {
            get {
                return ResourceManager.GetString("UI_StartDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string UI_StopWaiting {
            get {
                return ResourceManager.GetString("UI_StopWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page....
        /// </summary>
        public static string UI_UpdatePage {
            get {
                return ResourceManager.GetString("UI_UpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred during scanning for dependencies.
        /// </summary>
        public static string Unknown_error_occurred_during_scanning {
            get {
                return ResourceManager.GetString("Unknown_error_occurred_during_scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update NLO json file....
        /// </summary>
        public static string Update_NLO_json_file {
            get {
                return ResourceManager.GetString("Update_NLO_json_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default....
        /// </summary>
        public static string Use_default {
            get {
                return ResourceManager.GetString("Use_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RAG.
        /// </summary>
        public static string Use_RAG {
            get {
                return ResourceManager.GetString("Use_RAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual studio has no active FreeAIr options..
        /// </summary>
        public static string Visual_studio_has_no_active_FreeAIr {
            get {
                return ResourceManager.GetString("Visual_studio_has_no_active_FreeAIr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Visual Studio is a developer-related way, no FreeAIr artifacts falls in your github repo. The same FreeAIr options will be applied for every solution you opened..
        /// </summary>
        public static string Visual_Studio_is_a_developer_related {
            get {
                return ResourceManager.GetString("Visual_Studio_is_a_developer_related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for answer.
        /// </summary>
        public static string Waiting_for_answer {
            get {
                return ResourceManager.GetString("Waiting_for_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for status.
        /// </summary>
        public static string Waiting_for_status {
            get {
                return ResourceManager.GetString("Waiting_for_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole solution.
        /// </summary>
        public static string Whole_solution {
            get {
                return ResourceManager.GetString("Whole_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete stored options. Please, confirm..
        /// </summary>
        public static string You_are_going_to_delete_stored_options {
            get {
                return ResourceManager.GetString("You_are_going_to_delete_stored_options", resourceCulture);
            }
        }
    }
}
