// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FreeAIr
{
    internal sealed partial class Vsix
    {
        public const string Id = "FreeAIr.47ca033e-85ab-44c6-a9ff-5a56c7317ea7";
        public const string Name = "FreeAIr";
        public const string Description = @"Access to AI for free for anyone.";
        public const string Language = "en-US";
        public const string Version = "3.1.0";
        public const string Author = "lsoft";
        public const string Tags = "AI, Autocomplete, C#, Code Generation, Code Prediction, Code Snippets, Coding Accelerator, Coding Assistant, Developer Tools, IntelliCode, IntelliSense, LLM, Machine Learning, ML, Productivity, Suggestions";
        public const bool IsPreview = false;
    }
}
