// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FreeAIr
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FreeAIrString = "faec8da8-74ca-4afa-8b7d-64be3914fbac";
        public static Guid FreeAIr = new Guid(FreeAIrString);

        public const string FreeAIrImages16String = "83bcc0eb-7c0f-41ea-88e4-dc07cb510faf";
        public static Guid FreeAIrImages16 = new Guid(FreeAIrImages16String);

        public const string FreeAIrImages32String = "93bcc0eb-7c0f-41ea-88e4-dc07cb510faf";
        public static Guid FreeAIrImages32 = new Guid(FreeAIrImages32String);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ExtensionMenuGroup = 0x1003;
        public const int SubExtensionMenuGroup1 = 0x1004;
        public const int SubExtensionMenuGroup2 = 0x1005;
        public const int SubExtensionMenu = 0x1006;
        public const int ApplySupportCommandId = 0x1011;
        public const int StartDiscussionCommandId = 0x1012;
        public const int GenerateWholeLineSuggestionCommandId = 0x1013;
        public const int ChooseModelCommandId = 0x1014;
        public const int OpenChatListToolWindowCommandId = 0x1015;
        public const int SolutionTreeContextMenu = 0x1026;
        public const int SolutionTreeContextGroup = 0x1027;
        public const int ApplyFileSupportCommandId = 0x1028;
        public const int CodeLens_AddXmlCommentCommandId = 0x1036;
        public const int CodeLens_GenerateUnitTestsCommandId = 0x1037;
        public const int BuildErrorWindowGroup = 0x1039;
        public const int BuildErrorWindowFixErrorCommandId = 0x1040;
        public const int OpenNaturalSearchToolWindowCommandId = 0x1041;
        public const int ShowReleaseNotesCommandId = 0x1042;
        public const int OpenControlCenterCommandId = 0x1043;
        public const int AddNaturalLanguageOutlinesCommandId = 0x1052;
        public const int OpenBuildingNaturalLanguageOutlinesWindowCommandId = 0x1053;
        public const int OpenPropertiesCommandId = 0x1054;
        public const int AddFilesToContextCommandId = 0x1055;
        public const int OpenActivityLogCommandId = 0x1056;
        public const int OpenProxyLogCommandId = 0x1057;
        public const int ShowInSituChatCommandId = 0x1058;
        public const int VisualStudioContextMenu = 0x8000;
        public const int VisualStudioContextMenuGroup = 0x8001;
        public const int VisualStudioContextMenuDynamicCommandId = 0x8002;
        public const int Icon16 = 0x0001;
        public const int Icon32 = 0x0001;
    }
}
