// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FreeAIr
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FreeAIrString = "faec8da8-74ca-4afa-8b7d-64be3914fbac";
        public static Guid FreeAIr = new Guid(FreeAIrString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SourceCodeContextMenu = 0x1001;
        public const int SourceCodeContextGroup = 0x1011;
        public const int ExtensionMenuGroup = 0x1012;
        public const int SubExtensionMenuGroup = 0x1013;
        public const int SubExtensionMenu = 0x1014;
        public const int ExplainCommandId = 0x1021;
        public const int AddCommentsCommandId = 0x1022;
        public const int FreeAIrOptimizeCommandId = 0x1023;
        public const int CompleteCodeByCommentsCommandId = 0x1025;
        public const int FreeAIrChooseModelCommandId = 0x1027;
        public const int OpenChatListToolWindowCommandId = 0x1028;
        public const int StartDiscussionCommandId = 0x1029;
        public const int GenerateWholeLineSuggestionCommand = 0x1030;
        public const int SolutionContextMenu = 0x1031;
        public const int SolutionContextGroup = 0x1032;
        public const int ExplainFileCommandId = 0x1033;
        public const int AddCommentsToFileCommandId = 0x1034;
    }
}
