using System.Text.Json.Serialization;

namespace FreeAIr.NLOutline
{
    /// <summary>
    /// A single natural language outline: an LLM-written comment attached to a place in a source
    /// file. Outlines are generated by FreeAIr, reviewed by the user and then embedded into the
    /// code itself; later they are turned into embeddings for RAG.
    ///
    /// See https://arxiv.org/html/2408.04820v4 for the idea this follows.
    ///
    /// The property names are part of the format the LLM is asked to answer in — do not rename
    /// them without changing the corresponding prompt in the settings.
    /// </summary>
    public sealed class NaturalLanguageOutline
    {
        /// <summary>
        /// Path of the source file this outline comment belongs to, relative to the project or
        /// solution as reported by the LLM.
        /// </summary>
        [JsonPropertyName("file_path")]
        public string FilePath
        {
            get;
            set;
        }

        /// <summary>
        /// The line number in <see cref="FilePath"/> that the comment should be attached to.
        /// </summary>
        [JsonPropertyName("line")]
        public int Line
        {
            get;
            set;
        }

        /// <summary>
        /// The natural language comment text itself, written by the LLM for that line.
        /// </summary>
        [JsonPropertyName("comment")]
        public string Comment
        {
            get;
            set;
        }

        /// <summary>Creates an outline with empty defaults, ready for the deserializer to fill in.</summary>
        public NaturalLanguageOutline()
        {
            FilePath = string.Empty;
            Line = 0;
            Comment = string.Empty;
        }
    }
}
