using System.Text.Json.Serialization;

namespace FreeAIr.NLOutline
{
    /// <summary>
    /// A single natural language outline: an LLM-written comment attached to a place in a source
    /// file. Outlines are generated by FreeAIr, reviewed by the user and then embedded into the
    /// code itself; later they are turned into embeddings for RAG.
    ///
    /// See https://arxiv.org/html/2408.04820v4 for the idea this follows.
    ///
    /// The property names are part of the format the LLM is asked to answer in — do not rename
    /// them without changing the corresponding prompt in the settings.
    /// </summary>
    public sealed class NaturalLanguageOutline
    {
        [JsonPropertyName("file_path")]
        public string FilePath
        {
            get;
            set;
        }

        [JsonPropertyName("line")]
        public int Line
        {
            get;
            set;
        }

        [JsonPropertyName("comment")]
        public string Comment
        {
            get;
            set;
        }

        public NaturalLanguageOutline()
        {
            FilePath = string.Empty;
            Line = 0;
            Comment = string.Empty;
        }
    }
}
